version: '3.10'

services:


  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - "./scripts:/docker-entrypoint-initdb.d"

    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test


volumes:
  postgres_data:
